### ISSUE TITLE
Unable to disable user's 2FA

### ISSUE THREAD

**Issue by stevegrunwell** [ericmann/dovedi#6]
I had a case where I (as a site admin) needed to disable another user's 2FA code so they could log in and re-configure 2FA after a factory reset of their phone. Clicking the "Disable" button on their profile page gave me the JavaScript prompt, but didn't disable 2FA on their account (forcing me to manually clear the "_totp_key" record from `wp_usermeta`.

**Comment by ericmann** [comment]
Resolved with v1.1.1.
